# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
    
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    session:
        enabled: true
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    
    request:
        enabled: true
        formats:
            json: ['application/json']
    
    php_errors:
        log: true

    router:
        utf8: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
