monolog:
    channels: ['admin', 'messages']

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/dev.log"
                level: debug
                channels: ["!event"]
            admin:
                type: stream
                path: "%kernel.logs_dir%/admin.log"
                level: debug
                channels: ["admin"]
                formatter: monolog.formatter.json
            gallery:
                type: stream
                path: "%kernel.logs_dir%/gallery.log"
                level: debug
                channels: ["app"]
                formatter: monolog.formatter.json
            interests:
                type: stream
                path: "%kernel.logs_dir%/interests.log"
                level: debug
                channels: ["app"]
                formatter: monolog.formatter.json
            messages:
                type: stream
                path: "%kernel.logs_dir%/messages.log"
                level: debug
                channels: ["messages"]
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            admin:
                type: stream
                path: "%kernel.logs_dir%/admin.log"
                level: debug
                channels: ["admin"]
                formatter: monolog.formatter.json
            gallery:
                type: stream
                path: "%kernel.logs_dir%/gallery.log"
                level: debug
                channels: ["app"]
                formatter: monolog.formatter.json
            interests:
                type: stream
                path: "%kernel.logs_dir%/interests.log"
                level: debug
                channels: ["app"]
                formatter: monolog.formatter.json
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            admin:
                type: stream
                path: "%kernel.logs_dir%/admin.log"
                level: debug
                channels: ["admin"]
                formatter: monolog.formatter.json
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
